version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: tododb
    ports:
      - "${POSTGRES_PORT}:5432"
  api:
    build:
      context: .
      dockerfile: Source/Api/ToDo.Api/Dockerfile
    ports:
      - "${API_PORT}:80"
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: db
      POSTGRES_DB: example_db
  app:
    build:
      context: .
      dockerfile: Source/App/ToDo.App/Dockerfile
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - api
    environment:
      API_BASEURL: http://api:${API_PORT}
