version: '3'
networks:
  todo_network:
services:
  db:
    container_name: postgresdb
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    networks:
      - todo_network

  migrator:
    container_name: migratorapp
    build:
      context: .
      dockerfile: Source/Migrator/Migrator.App/Dockerfile
    depends_on:
      - db
    env_file:
      - .env    
    networks:
      - todo_network
  
  api:
    container_name: todoapi
    build:
      context: .
      dockerfile: Source/Api/ToDo.Api/Dockerfile
    restart: always
    depends_on:
      - migrator
      - db
    ports:
      - "${API_PORT:-8000}:80"
    env_file:
      - .env
    networks:
      - todo_network
  app:
    container_name: todoapp
    build:
      context: .
      dockerfile: Source/App/ToDo.App/Dockerfile
    restart: always
    depends_on:
      - api
    ports:
      - "${APP_PORT:-5000}:80"
    env_file:
      - .env
    networks:
      - todo_network
